# remote_theme: alshedivat/al-folio
# remote_theme: poole/lanyon (not working with remote_theme reather fork)
# remote_theme: daattali/beautiful-jekyll
# remote_theme: pages-themes/primer

permalink: pretty

plugins:
- jekyll-redirect-from
- jekyll-include-cache
