title: Putins Kriegsführung
description: |-
  beeinflusst putins Propaganda die Demokratie Deutschlands?
  Die online Version unserer Seminararbeit.
keywords: ["Seminararbeit", "hybride Kriegsführung", "Putin", "Propaganda", "Deutschland", "Demokratie", "Putins Kriegsführung"]
css_theme: default
paginate_to: 3
theme-color: "#7aaff3"

permalink: pretty
    
defaults:
  -  scope:
      path: "seite/*.md"
    values:
      paginate: true
      
sass:
    style: compressed
    
plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-include-cache
