title: Putins Kriegsführung
description: |-
  beeinflusst putins Propaganda die Demokratie Deutschlands?
  Die online Version unserer Seminararbeit.
keywords: ["Seminararbeit", "hybride Kriegsführung", "Putin", "Propaganda", "Deutschland", "Demokratie", "Putins Kriegsführung"]
css_theme: default
theme-color: "#7aaff3"
permalink: pretty

sass:
    style: compressed
    
exclude:
- LICENCE
- *.md

plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-include-cache
